# -*- coding: utf-8 -*-
"""Product metadata for professional multi-angle generation."""
PRODUCTS = [
  ("dry-robe-sand", "Cape Dry Robe", "sand cream microfibre dog drying robe with navy trim and tan leather DRY & CO patch, folded"),
  ("dry-robe-navy", "Harbour Dry Coat", "navy dog drying coat with leather DRY & CO badge"),
  ("check-blanket", "Estate Check Blanket", "navy and ivory buffalo check dog blanket with leather patch"),
  ("travel-mat", "Winelands Travel Mat", "stone waterproof fold-flat dog travel mat"),
  ("boucle-bed", "Constantia Bouclé Bed", "oatmeal bouclé orthopedic luxury dog bed"),
  ("leather-collar", "leather dog collar", "tan cognac leather dog collar with brass hardware"),
  ("leather-lead", "leather dog lead", "tan leather dog lead/leash coiled with brass clip"),
  ("harness", "leather dog harness", "tan leather dog harness with brass hardware"),
  ("treat-pouch", "leather treat pouch", "tan leather dog treat pouch"),
  ("ceramic-bowls", "ceramic dog bowls", "pair of ivory ceramic dog bowls"),
  ("elevated-feeder", "elevated dog feeder", "wooden elevated dog feeder stand with bowls"),
  ("boot-liner", "car boot liner", "waterproof quilted car boot dog liner in charcoal"),
  ("bandana", "dog bandana", "navy ivory check dog bandana"),
  ("knit-jumper", "dog knit jumper", "cream cable-knit dog sweater"),
  ("calm-mist", "calm mist spray bottle", "amber glass pet calm mist spray bottle with label"),
  ("dry-shampoo", "dog dry shampoo", "matte bottle of dog dry shampoo"),
  ("towel-set", "dog towel set", "folded ivory and navy dog towels"),
  ("name-tag", "brass dog name tag", "brass circular dog ID name tag"),
  ("rain-shell", "dog rain shell", "navy lightweight dog rain jacket"),
  ("car-hammock", "car hammock", "charcoal dog car seat hammock"),
  ("paw-butter", "paw butter jar", "small amber jar of dog paw butter balm"),
  ("cooling-mat", "cooling mat", "gel dog cooling mat in soft blue-grey"),
  ("felt-toys", "felt dog toys", "set of wool felt luxury dog toys"),
  ("brass-hook", "brass leash hook", "wall-mounted brass dog leash hook"),
  ("window-perch", "window perch", "beige cat/dog window perch cushion"),
  ("rain-candle", "scented candle", "amber glass candle jar for home"),
  ("denim-jacket", "dog denim jacket", "indigo denim dog jacket with leather patch"),
  ("cat-cave", "cat cave nest", "soft boucle cloud cat cave bed"),
  ("cat-tree", "cat tower", "modern timber and boucle cat tree tower"),
  ("cat-fountain", "cat fountain", "ceramic pet water fountain"),
  ("cat-toys", "cat toys", "set of elegant cat hunt toys"),
  ("cat-collar", "cat collar", "velvet breakaway cat collar with bell"),
  ("litter-cabinet", "litter cabinet", "furniture-style hidden litter box cabinet"),
  ("cat-hammock", "cat hammock", "radiator or window cat hammock"),
  ("cat-groom", "cat grooming set", "luxury cat brush and groom tools"),
  ("cat-carrier", "cat carrier", "soft-sided premium cat carrier"),
  ("cat-tunnel", "cat tunnel", "fabric cat play tunnel"),
  ("cat-diner", "cat diner bowls", "elevated ceramic cat bowl set"),
  ("cat-blanket", "cat blanket", "soft lap throw blanket for cats"),
  ("cat-shelves", "cat wall shelves", "modern wall-mounted cat shelves"),
  ("cat-catnip", "catnip pouch", "linen pouch of organic catnip"),
  ("cat-scratcher", "cat scratcher", "modern sisal cat scratcher lounge"),
  ("cat-harness", "cat harness", "soft escape-proof cat harness and lead"),
]
